<div id="topbar" class="clearfix">

	<a href="http://www.milwaukeetool.com/" target='_blank' class="logo round-all">
		<img src="http://blog.toolhq.com.au/wp-content/uploads/2012/05/Milwaukee-Logo.jpg" width="200" height="70" alt="" />
	</a>




	<div class="user_box dark_box clearfix" rel='tooltip' data-html='true' title='Informações do usuário.<br />Clique na imagem para ver seu perfil!'
		 data-placement='left' data-html='true'>
		<img src='http://posvenda.telecontrol.com.br/assist/admin/admin_fotos/tbl_admin.1553.jpg' id='adm_foto' width="55" class="img-rounded" alt="Profile Pic" onClick='toggleCustomizePopUp("admCfgFrm")' />
		<h2>Waldir Pimentel</h2>
		<h3><a class="text_shadow bold" href="#">waldir</a></h3>
		<ul>
			<li><a href='javascript:toggleCustomizePopUp("admCfgFrm")' rel='tooltip' data-placement='bottom' title='Seu perfil de usuário'>Perfil</a><span class="divider">|</span></li>
			<li><a href="admin_senha_n.php?mostrar=so_usuario" rel='tooltip' data-placement='bottom' title='Permissões e dados do cadastro'>Cadastro</a><span class="divider">|</span></li>
			<!-- <li><a href="logout.php" class="dialog_button" rel='tooltip' data-placement='bottom' title='Encerrar sessão.'>Sair</a></li> -->
		</ul>
	</div><!-- #user_box -->

</div><!-- #topbar -->