<?php
$form = $this->form;
$form->setAttribute('action', $this->url('home', array('action' => 'add')));
$form->prepare();
?>


<div class="row">

    <div class="span12">
        <?php
            echo $this->formRow($form->get('os'));
            echo $this->formRow($form->get('serie'));
            echo $this->formRow($form->get('nf'));
            echo $this->formRow($form->get('cpf'));
            echo $this->formRow($form->get('tipo_os'));
            echo $this->formRow($form->get('tipo_atendimento'));
            echo $this->formRow($form->get('status_os'));
            echo $this->formRow($form->get('submit_1'));
        ?>
    </div>
</div>
